import numpy as np
import csv
import io
from .TimeSeries import TimeSeries


def block_divider(text):
    """Split entire text into different cycle blocks (delimiter: \n\n,)
    """
    return text.strip().split('\n\n')
    

def block_parser(text):
    """
    Args
        test (string):
    Returns
        (ForceTimeSeries): 
    """
    f = io.StringIO(text)
    reader = csv.reader(f)

    cycle = next(reader)  # "[1Cycle]"
    header = next(reader)  # "Time","Force","Stroke","Cycle"
    units = next(reader)  # "sec","N","mm",""

    ret = TimeSeries()
    for row in reader:
        ret.append(float(row[0]), float(row[1]))

    f.close()

    return ret


def force_data_read(file_path):
    """Read csv data generated by mechanical tester
    """
    f = open(file_path, 'r')
    text = f.read()
    blocks = block_divider(text)

    ret = TimeSeries()
    for blk in blocks:
        ret.extend(block_parser(blk))

    f.close()
    return ret